services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env      
    volumes:
      - db_data_2Tier:/var/lib/mysql     

    networks:
      - app-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "--user=ibtisam", "--password=ibtisam"]  
      interval: 30s
      timeout: 10s
      retries: 3

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    image: 1-single-backend-container-serves-both-the-api-and-static-frontend-files
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"                  # Expose app on port 5000
    depends_on:
      db:
        condition: service_healthy   # Wait for MySQL to be healthy before starting the app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data_2Tier:
